### ISSUE TITLE
Add tsconfig nodenext for ESM

### ISSUE THREAD

**Issue by yordis** [straw-hat-team/nodejs-monorepo#17]
### Problem Statement

After the following issue is resolved: https://github.com/microsoft/TypeScript/issues/46452#issuecomment-1072864111

### Solution Brainstorm

Add to the `tsconfig` base config

```json
{
  "module": "nodenext",
  "moduleResolution": "nodenext"
}
```

**Comment by frank-dspeed** [comment]
@yordis do not do that this is not a good idea let me explain that when you switch to nodenext you will only be able to consume nodenext compatible packages that include a exports fild there are a lot of packages that do not contain that fild

create a tsconfig that uses nodenext and include there all folders to modules that use exports and create a secund that  uses moduleResolve mode node to use the main fild of the package.json

the moduleResolution mode is a per package thing not a per Project thing it depends on your dependencies that you consume 

alternativ you could create folders and link them with npm and put there a valid package.json with a exports fild. then you can  use nodenext for everything.

**Comment by yordis** [comment]
@frank-dspeed before anything, I really appreciate all the work you are putting on in that thread and even more that you help me over there. Thank you, I don't take it for granted.

And ... what a mess this topic, not gonna lie, I am burned out by the complexity and all the edge-cases by now.

> the moduleResolution mode is a per package thing not a per Project thing it depends on your dependencies that you consume

https://github.com/straw-hat-team/nodejs-monorepo/blob/29fa1a6058df6ccc9d5638091f8fc295bf9e9071/packages/%40straw-hat/tsconfig/lib/base.json#L9-L10 when I say add it to the `tsconfig` it thereby defaults so people can use that without having to worry about it.

> you will only be able to consume nodenext compatible packages that include a exports fild there are a lot of packages that do not contain that field

I didn't know this, if that is the case, no way I should use that as default then.

Why would I bother then to use that at all then? Makes no sense to fallback to some other behavior or something like that.

**Comment by frank-dspeed** [comment]
@yordis as rule of thumb when you depend on npm packages use as default moduleResolution: node that enables that typescript looks into node_modules/**/package.json and everything is fine most of the time but as soon as you will get a dependencie that does not resolve via that mode and you then look into its package.json you will probally have a so called nodenext or node12 package that packages contain no main: fild they contain only exports:

this will not resolve via moduleResolve: node only if they also got a file index.d.ts then they could maybe resolve but lets skip that details if they do not resolve its time to throw the new moduleResolution mode into the game

you will create a folder nodenext-dependencies then you will create a tsconfig.json in that folder and then you will there enable moduleResolution: nodenext

then you will put a file in that folder that reexports that package exports * from 'nodenext-package-name', then you will enable the composit flag for that project and go with this explained pattern that is called referenced projects or sub projects pattern

https://www.typescriptlang.org/docs/handbook/project-references.html

hope that helps you a bit.

**Comment by yordis** [comment]
Definitely helps a lot! I think I will ignore the `nodenext` for now and let people to opt-in, the intention is to have sane defaults for the base tsconfig ... but I don't think this one is one of them honestly. 

Thank you so much, I may come back to this next year 😄
